// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwxgfjypcgvmaqftnzdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3eGdmanlwY2d2bWFxZnRuemRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MDI1NzgsImV4cCI6MjA2MjE3ODU3OH0.aMfMwK3FbBHod0lcAOqOfUamCSkFnv-Ny6TCiw_VgEY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);